import { Country, CurrencyOption } from "@/types/auth";

export const countries: Country[] = [
  { code: "US", name: "United States", flag: "🇺🇸", phoneCode: "+1" },
  { code: "CA", name: "Canada", flag: "🇨🇦", phoneCode: "+1" },
  { code: "GB", name: "United Kingdom", flag: "🇬🇧", phoneCode: "+44" },
  { code: "FR", name: "France", flag: "🇫🇷", phoneCode: "+33" },
  { code: "DE", name: "Germany", flag: "🇩🇪", phoneCode: "+49" },
  { code: "IT", name: "Italy", flag: "🇮🇹", phoneCode: "+39" },
  { code: "ES", name: "Spain", flag: "🇪🇸", phoneCode: "+34" },
  { code: "NL", name: "Netherlands", flag: "🇳🇱", phoneCode: "+31" },
  { code: "BE", name: "Belgium", flag: "🇧🇪", phoneCode: "+32" },
  { code: "CH", name: "Switzerland", flag: "🇨🇭", phoneCode: "+41" },
  { code: "AT", name: "Austria", flag: "🇦🇹", phoneCode: "+43" },
  { code: "DK", name: "Denmark", flag: "🇩🇰", phoneCode: "+45" },
  { code: "SE", name: "Sweden", flag: "🇸🇪", phoneCode: "+46" },
  { code: "NO", name: "Norway", flag: "🇳🇴", phoneCode: "+47" },
  { code: "FI", name: "Finland", flag: "🇫🇮", phoneCode: "+358" },
  { code: "PL", name: "Poland", flag: "🇵🇱", phoneCode: "+48" },
  { code: "CZ", name: "Czech Republic", flag: "🇨🇿", phoneCode: "+420" },
  { code: "HU", name: "Hungary", flag: "🇭🇺", phoneCode: "+36" },
  { code: "RO", name: "Romania", flag: "🇷🇴", phoneCode: "+40" },
  { code: "BG", name: "Bulgaria", flag: "🇧🇬", phoneCode: "+359" },
  { code: "HR", name: "Croatia", flag: "🇭🇷", phoneCode: "+385" },
  { code: "SI", name: "Slovenia", flag: "🇸🇮", phoneCode: "+386" },
  { code: "SK", name: "Slovakia", flag: "🇸🇰", phoneCode: "+421" },
  { code: "LT", name: "Lithuania", flag: "🇱🇹", phoneCode: "+370" },
  { code: "LV", name: "Latvia", flag: "🇱🇻", phoneCode: "+371" },
  { code: "EE", name: "Estonia", flag: "🇪🇪", phoneCode: "+372" },
  { code: "RU", name: "Russia", flag: "🇷🇺", phoneCode: "+7" },
  { code: "UA", name: "Ukraine", flag: "🇺🇦", phoneCode: "+380" },
  { code: "BY", name: "Belarus", flag: "🇧🇾", phoneCode: "+375" },
  { code: "JP", name: "Japan", flag: "🇯🇵", phoneCode: "+81" },
  { code: "KR", name: "South Korea", flag: "🇰🇷", phoneCode: "+82" },
  { code: "CN", name: "China", flag: "🇨🇳", phoneCode: "+86" },
  { code: "HK", name: "Hong Kong", flag: "🇭🇰", phoneCode: "+852" },
  { code: "MO", name: "Macau", flag: "🇲🇴", phoneCode: "+853" },
  { code: "TW", name: "Taiwan", flag: "🇹🇼", phoneCode: "+886" },
  { code: "SG", name: "Singapore", flag: "🇸🇬", phoneCode: "+65" },
  { code: "MY", name: "Malaysia", flag: "🇲🇾", phoneCode: "+60" },
  { code: "TH", name: "Thailand", flag: "🇹🇭", phoneCode: "+66" },
  { code: "VN", name: "Vietnam", flag: "🇻🇳", phoneCode: "+84" },
  { code: "PH", name: "Philippines", flag: "🇵🇭", phoneCode: "+63" },
  { code: "ID", name: "Indonesia", flag: "🇮🇩", phoneCode: "+62" },
  { code: "IN", name: "India", flag: "🇮🇳", phoneCode: "+91" },
  { code: "PK", name: "Pakistan", flag: "🇵🇰", phoneCode: "+92" },
  { code: "BD", name: "Bangladesh", flag: "🇧🇩", phoneCode: "+880" },
  { code: "LK", name: "Sri Lanka", flag: "🇱🇰", phoneCode: "+94" },
  { code: "NP", name: "Nepal", flag: "🇳🇵", phoneCode: "+977" },
  { code: "BT", name: "Bhutan", flag: "🇧🇹", phoneCode: "+975" },
  { code: "AF", name: "Afghanistan", flag: "🇦🇫", phoneCode: "+93" },
  { code: "IR", name: "Iran", flag: "🇮🇷", phoneCode: "+98" },
  { code: "IQ", name: "Iraq", flag: "🇮🇶", phoneCode: "+964" },
  { code: "TR", name: "Turkey", flag: "🇹🇷", phoneCode: "+90" },
  { code: "IL", name: "Israel", flag: "🇮🇱", phoneCode: "+972" },
  { code: "PS", name: "Palestine", flag: "🇵🇸", phoneCode: "+970" },
  { code: "LB", name: "Lebanon", flag: "🇱🇧", phoneCode: "+961" },
  { code: "SY", name: "Syria", flag: "🇸🇾", phoneCode: "+963" },
  { code: "JO", name: "Jordan", flag: "🇯🇴", phoneCode: "+962" },
  { code: "KW", name: "Kuwait", flag: "🇰🇼", phoneCode: "+965" },
  { code: "QA", name: "Qatar", flag: "🇶🇦", phoneCode: "+974" },
  { code: "BH", name: "Bahrain", flag: "🇧🇭", phoneCode: "+973" },
  { code: "AE", name: "United Arab Emirates", flag: "🇦🇪", phoneCode: "+971" },
  { code: "OM", name: "Oman", flag: "🇴🇲", phoneCode: "+968" },
  { code: "SA", name: "Saudi Arabia", flag: "🇸🇦", phoneCode: "+966" },
  { code: "YE", name: "Yemen", flag: "🇾🇪", phoneCode: "+967" },
  { code: "EG", name: "Egypt", flag: "🇪🇬", phoneCode: "+20" },
  { code: "ZA", name: "South Africa", flag: "🇿🇦", phoneCode: "+27" },
  { code: "NG", name: "Nigeria", flag: "🇳🇬", phoneCode: "+234" },
  { code: "KE", name: "Kenya", flag: "🇰🇪", phoneCode: "+254" },
  { code: "UG", name: "Uganda", flag: "🇺🇬", phoneCode: "+256" },
  { code: "TZ", name: "Tanzania", flag: "🇹🇿", phoneCode: "+255" },
  { code: "ET", name: "Ethiopia", flag: "🇪🇹", phoneCode: "+251" },
  { code: "GH", name: "Ghana", flag: "🇬🇭", phoneCode: "+233" },
  { code: "CI", name: "Ivory Coast", flag: "🇨🇮", phoneCode: "+225" },
  { code: "BF", name: "Burkina Faso", flag: "🇧🇫", phoneCode: "+226" },
  { code: "NE", name: "Niger", flag: "🇳🇪", phoneCode: "+227" },
  { code: "TG", name: "Togo", flag: "🇹🇬", phoneCode: "+228" },
  { code: "BJ", name: "Benin", flag: "🇧🇯", phoneCode: "+229" },
  { code: "MU", name: "Mauritius", flag: "🇲🇺", phoneCode: "+230" },
  { code: "LR", name: "Liberia", flag: "🇱🇷", phoneCode: "+231" },
  { code: "SL", name: "Sierra Leone", flag: "🇸🇱", phoneCode: "+232" },
  { code: "TD", name: "Chad", flag: "🇹🇩", phoneCode: "+235" },
  {
    code: "CF",
    name: "Central African Republic",
    flag: "🇨🇫",
    phoneCode: "+236",
  },
  { code: "CM", name: "Cameroon", flag: "🇨🇲", phoneCode: "+237" },
  { code: "CV", name: "Cape Verde", flag: "🇨🇻", phoneCode: "+238" },
  { code: "ST", name: "São Tomé and Príncipe", flag: "🇸🇹", phoneCode: "+239" },
  { code: "GQ", name: "Equatorial Guinea", flag: "🇬🇶", phoneCode: "+240" },
  { code: "GA", name: "Gabon", flag: "🇬🇦", phoneCode: "+241" },
  { code: "CG", name: "Republic of the Congo", flag: "🇨🇬", phoneCode: "+242" },
  {
    code: "CD",
    name: "Democratic Republic of the Congo",
    flag: "🇨🇩",
    phoneCode: "+243",
  },
  { code: "AO", name: "Angola", flag: "🇦🇴", phoneCode: "+244" },
  { code: "GW", name: "Guinea-Bissau", flag: "🇬🇼", phoneCode: "+245" },
  { code: "SC", name: "Seychelles", flag: "🇸🇨", phoneCode: "+248" },
  { code: "SD", name: "Sudan", flag: "🇸🇩", phoneCode: "+249" },
  { code: "RW", name: "Rwanda", flag: "🇷🇼", phoneCode: "+250" },
  { code: "SO", name: "Somalia", flag: "🇸🇴", phoneCode: "+252" },
  { code: "DJ", name: "Djibouti", flag: "🇩🇯", phoneCode: "+253" },
  { code: "BI", name: "Burundi", flag: "🇧🇮", phoneCode: "+257" },
  { code: "MZ", name: "Mozambique", flag: "🇲🇿", phoneCode: "+258" },
  { code: "ZM", name: "Zambia", flag: "🇿🇲", phoneCode: "+260" },
  { code: "MG", name: "Madagascar", flag: "🇲🇬", phoneCode: "+261" },
  { code: "ZW", name: "Zimbabwe", flag: "🇿🇼", phoneCode: "+263" },
  { code: "NA", name: "Namibia", flag: "🇳🇦", phoneCode: "+264" },
  { code: "MW", name: "Malawi", flag: "🇲🇼", phoneCode: "+265" },
  { code: "LS", name: "Lesotho", flag: "🇱🇸", phoneCode: "+266" },
  { code: "BW", name: "Botswana", flag: "🇧🇼", phoneCode: "+267" },
  { code: "SZ", name: "Eswatini", flag: "🇸🇿", phoneCode: "+268" },
  { code: "KM", name: "Comoros", flag: "🇰🇲", phoneCode: "+269" },
  { code: "SH", name: "Saint Helena", flag: "🇸🇭", phoneCode: "+290" },
  { code: "ER", name: "Eritrea", flag: "🇪🇷", phoneCode: "+291" },
  { code: "AW", name: "Aruba", flag: "🇦🇼", phoneCode: "+297" },
  { code: "FO", name: "Faroe Islands", flag: "🇫🇴", phoneCode: "+298" },
  { code: "GL", name: "Greenland", flag: "🇬🇱", phoneCode: "+299" },
  { code: "GI", name: "Gibraltar", flag: "🇬🇮", phoneCode: "+350" },
  { code: "PT", name: "Portugal", flag: "🇵🇹", phoneCode: "+351" },
  { code: "LU", name: "Luxembourg", flag: "🇱🇺", phoneCode: "+352" },
  { code: "IE", name: "Ireland", flag: "🇮🇪", phoneCode: "+353" },
  { code: "IS", name: "Iceland", flag: "🇮🇸", phoneCode: "+354" },
  { code: "AL", name: "Albania", flag: "🇦🇱", phoneCode: "+355" },
  { code: "MT", name: "Malta", flag: "🇲🇹", phoneCode: "+356" },
  { code: "CY", name: "Cyprus", flag: "🇨🇾", phoneCode: "+357" },
  { code: "MD", name: "Moldova", flag: "🇲🇩", phoneCode: "+373" },
  { code: "AM", name: "Armenia", flag: "🇦🇲", phoneCode: "+374" },
  { code: "AD", name: "Andorra", flag: "🇦🇩", phoneCode: "+376" },
  { code: "MC", name: "Monaco", flag: "🇲🇨", phoneCode: "+377" },
  { code: "SM", name: "San Marino", flag: "🇸🇲", phoneCode: "+378" },
  { code: "RS", name: "Serbia", flag: "🇷🇸", phoneCode: "+381" },
  { code: "ME", name: "Montenegro", flag: "🇲🇪", phoneCode: "+382" },
  { code: "XK", name: "Kosovo", flag: "🇽🇰", phoneCode: "+383" },
  { code: "BA", name: "Bosnia and Herzegovina", flag: "🇧🇦", phoneCode: "+387" },
  { code: "MK", name: "North Macedonia", flag: "🇲🇰", phoneCode: "+389" },
  { code: "LI", name: "Liechtenstein", flag: "🇱🇮", phoneCode: "+423" },
  { code: "FK", name: "Falkland Islands", flag: "🇫🇰", phoneCode: "+500" },
  { code: "BZ", name: "Belize", flag: "🇧🇿", phoneCode: "+501" },
  { code: "GT", name: "Guatemala", flag: "🇬🇹", phoneCode: "+502" },
  { code: "SV", name: "El Salvador", flag: "🇸🇻", phoneCode: "+503" },
  { code: "HN", name: "Honduras", flag: "🇭🇳", phoneCode: "+504" },
  { code: "NI", name: "Nicaragua", flag: "🇳🇮", phoneCode: "+505" },
  { code: "CR", name: "Costa Rica", flag: "🇨🇷", phoneCode: "+506" },
  { code: "PA", name: "Panama", flag: "🇵🇦", phoneCode: "+507" },
  {
    code: "PM",
    name: "Saint Pierre and Miquelon",
    flag: "🇵🇲",
    phoneCode: "+508",
  },
  { code: "HT", name: "Haiti", flag: "🇭🇹", phoneCode: "+509" },
  { code: "GP", name: "Guadeloupe", flag: "🇬🇵", phoneCode: "+590" },
  { code: "BO", name: "Bolivia", flag: "🇧🇴", phoneCode: "+591" },
  { code: "GY", name: "Guyana", flag: "🇬🇾", phoneCode: "+592" },
  { code: "EC", name: "Ecuador", flag: "🇪🇨", phoneCode: "+593" },
  { code: "GF", name: "French Guiana", flag: "🇬🇫", phoneCode: "+594" },
  { code: "PY", name: "Paraguay", flag: "🇵🇾", phoneCode: "+595" },
  { code: "MQ", name: "Martinique", flag: "🇲🇶", phoneCode: "+596" },
  { code: "SR", name: "Suriname", flag: "🇸🇷", phoneCode: "+597" },
  { code: "UY", name: "Uruguay", flag: "🇺🇾", phoneCode: "+598" },
  { code: "BQ", name: "Caribbean Netherlands", flag: "🇧🇶", phoneCode: "+599" },
  { code: "TL", name: "East Timor", flag: "🇹🇱", phoneCode: "+670" },
  { code: "AQ", name: "Antarctica", flag: "🇦🇶", phoneCode: "+672" },
  { code: "BN", name: "Brunei", flag: "🇧🇳", phoneCode: "+673" },
  { code: "NR", name: "Nauru", flag: "🇳🇷", phoneCode: "+674" },
  { code: "PG", name: "Papua New Guinea", flag: "🇵🇬", phoneCode: "+675" },
  { code: "TO", name: "Tonga", flag: "🇹🇴", phoneCode: "+676" },
  { code: "SB", name: "Solomon Islands", flag: "🇸🇧", phoneCode: "+677" },
  { code: "VU", name: "Vanuatu", flag: "🇻🇺", phoneCode: "+678" },
  { code: "FJ", name: "Fiji", flag: "🇫🇯", phoneCode: "+679" },
  { code: "PW", name: "Palau", flag: "🇵🇼", phoneCode: "+680" },
  { code: "WF", name: "Wallis and Futuna", flag: "🇼🇫", phoneCode: "+681" },
  { code: "CK", name: "Cook Islands", flag: "🇨🇰", phoneCode: "+682" },
  { code: "NU", name: "Niue", flag: "🇳🇺", phoneCode: "+683" },
  { code: "AS", name: "American Samoa", flag: "🇦🇸", phoneCode: "+684" },
  { code: "WS", name: "Samoa", flag: "🇼🇸", phoneCode: "+685" },
  { code: "KI", name: "Kiribati", flag: "🇰🇮", phoneCode: "+686" },
  { code: "NC", name: "New Caledonia", flag: "🇳🇨", phoneCode: "+687" },
  { code: "TV", name: "Tuvalu", flag: "🇹🇻", phoneCode: "+688" },
  { code: "PF", name: "French Polynesia", flag: "🇵🇫", phoneCode: "+689" },
  { code: "TK", name: "Tokelau", flag: "🇹🇰", phoneCode: "+690" },
  { code: "FM", name: "Micronesia", flag: "🇫🇲", phoneCode: "+691" },
  { code: "MH", name: "Marshall Islands", flag: "🇲🇭", phoneCode: "+692" },
  { code: "KP", name: "North Korea", flag: "🇰🇵", phoneCode: "+850" },
  { code: "KH", name: "Cambodia", flag: "🇰🇭", phoneCode: "+855" },
  { code: "LA", name: "Laos", flag: "🇱🇦", phoneCode: "+856" },
  { code: "MV", name: "Maldives", flag: "🇲🇻", phoneCode: "+960" },
  { code: "MN", name: "Mongolia", flag: "🇲🇳", phoneCode: "+976" },
  { code: "TJ", name: "Tajikistan", flag: "🇹🇯", phoneCode: "+992" },
  { code: "TM", name: "Turkmenistan", flag: "🇹🇲", phoneCode: "+993" },
  { code: "AZ", name: "Azerbaijan", flag: "🇦🇿", phoneCode: "+994" },
  { code: "GE", name: "Georgia", flag: "🇬🇪", phoneCode: "+995" },
  { code: "KG", name: "Kyrgyzstan", flag: "🇰🇬", phoneCode: "+996" },
  { code: "UZ", name: "Uzbekistan", flag: "🇺🇿", phoneCode: "+998" },
  { code: "BS", name: "Bahamas", flag: "🇧🇸", phoneCode: "+1242" },
  { code: "BB", name: "Barbados", flag: "🇧🇧", phoneCode: "+1246" },
  { code: "AI", name: "Anguilla", flag: "🇦🇮", phoneCode: "+1264" },
  { code: "AG", name: "Antigua and Barbuda", flag: "🇦🇬", phoneCode: "+1268" },
  {
    code: "VG",
    name: "British Virgin Islands",
    flag: "🇻🇬",
    phoneCode: "+1284",
  },
  { code: "VI", name: "US Virgin Islands", flag: "🇻🇮", phoneCode: "+1340" },
  { code: "KY", name: "Cayman Islands", flag: "🇰🇾", phoneCode: "+1345" },
  { code: "BM", name: "Bermuda", flag: "🇧🇲", phoneCode: "+1441" },
  { code: "GD", name: "Grenada", flag: "🇬🇩", phoneCode: "+1473" },
  {
    code: "TC",
    name: "Turks and Caicos Islands",
    flag: "🇹🇨",
    phoneCode: "+1649",
  },
  { code: "MS", name: "Montserrat", flag: "🇲🇸", phoneCode: "+1664" },
  {
    code: "MP",
    name: "Northern Mariana Islands",
    flag: "🇲🇵",
    phoneCode: "+1670",
  },
  { code: "GU", name: "Guam", flag: "🇬🇺", phoneCode: "+1671" },
  { code: "SX", name: "Sint Maarten", flag: "🇸🇽", phoneCode: "+1721" },
  { code: "LC", name: "Saint Lucia", flag: "🇱🇨", phoneCode: "+1758" },
  { code: "DM", name: "Dominica", flag: "🇩🇲", phoneCode: "+1767" },
  {
    code: "VC",
    name: "Saint Vincent and the Grenadines",
    flag: "🇻🇨",
    phoneCode: "+1784",
  },
  { code: "PR", name: "Puerto Rico", flag: "🇵🇷", phoneCode: "+1787" },
  { code: "DO", name: "Dominican Republic", flag: "🇩🇴", phoneCode: "+1809" },
  { code: "TT", name: "Trinidad and Tobago", flag: "🇹🇹", phoneCode: "+1868" },
  { code: "KN", name: "Saint Kitts and Nevis", flag: "🇰🇳", phoneCode: "+1869" },
  { code: "JM", name: "Jamaica", flag: "🇯🇲", phoneCode: "+1876" },
  { code: "AU", name: "Australia", flag: "🇦🇺", phoneCode: "+61" },
  { code: "NZ", name: "New Zealand", flag: "🇳🇿", phoneCode: "+64" },
  { code: "MX", name: "Mexico", flag: "🇲🇽", phoneCode: "+52" },
  { code: "BR", name: "Brazil", flag: "🇧🇷", phoneCode: "+55" },
  { code: "AR", name: "Argentina", flag: "🇦🇷", phoneCode: "+54" },
  { code: "CL", name: "Chile", flag: "🇨🇱", phoneCode: "+56" },
  { code: "CO", name: "Colombia", flag: "🇨🇴", phoneCode: "+57" },
  { code: "VE", name: "Venezuela", flag: "🇻🇪", phoneCode: "+58" },
  { code: "PE", name: "Peru", flag: "🇵🇪", phoneCode: "+51" },
];

export const currencyOptions: CurrencyOption[] = [
  { value: "USD", label: "🇺🇸 US Dollar (USD)" },
  { value: "EUR", label: "🇪🇺 Euro (EUR)" },
  { value: "GBP", label: "🇬🇧 British Pound (GBP)" },
  { value: "JPY", label: "🇯🇵 Japanese Yen (JPY)" },
  { value: "CAD", label: "🇨🇦 Canadian Dollar (CAD)" },
  { value: "AUD", label: "🇦🇺 Australian Dollar (AUD)" },
  { value: "CHF", label: "🇨🇭 Swiss Franc (CHF)" },
  { value: "CNY", label: "🇨🇳 Chinese Yuan (CNY)" },
  { value: "SEK", label: "🇸🇪 Swedish Krona (SEK)" },
  { value: "NZD", label: "🇳🇿 New Zealand Dollar (NZD)" },
  { value: "MXN", label: "🇲🇽 Mexican Peso (MXN)" },
  { value: "SGD", label: "🇸🇬 Singapore Dollar (SGD)" },
  { value: "HKD", label: "🇭🇰 Hong Kong Dollar (HKD)" },
  { value: "NOK", label: "🇳🇴 Norwegian Krone (NOK)" },
  { value: "TRY", label: "🇹🇷 Turkish Lira (TRY)" },
  { value: "RUB", label: "🇷🇺 Russian Ruble (RUB)" },
  { value: "INR", label: "🇮🇳 Indian Rupee (INR)" },
  { value: "BRL", label: "🇧🇷 Brazilian Real (BRL)" },
  { value: "ZAR", label: "🇿🇦 South African Rand (ZAR)" },
  { value: "KRW", label: "🇰🇷 South Korean Won (KRW)" },
  { value: "PLN", label: "🇵🇱 Polish Zloty (PLN)" },
  { value: "ILS", label: "🇮🇱 Israeli Shekel (ILS)" },
  { value: "DKK", label: "🇩🇰 Danish Krone (DKK)" },
  { value: "TWD", label: "🇹🇼 Taiwan Dollar (TWD)" },
  { value: "THB", label: "🇹🇭 Thai Baht (THB)" },
  { value: "MYR", label: "🇲🇾 Malaysian Ringgit (MYR)" },
  { value: "PHP", label: "🇵🇭 Philippine Peso (PHP)" },
  { value: "IDR", label: "🇮🇩 Indonesian Rupiah (IDR)" },
  { value: "VND", label: "🇻🇳 Vietnamese Dong (VND)" },
  { value: "AED", label: "🇦🇪 UAE Dirham (AED)" },
  { value: "SAR", label: "🇸🇦 Saudi Riyal (SAR)" },
  { value: "QAR", label: "🇶🇦 Qatari Riyal (QAR)" },
  { value: "KWD", label: "🇰🇼 Kuwaiti Dinar (KWD)" },
  { value: "BHD", label: "🇧🇭 Bahraini Dinar (BHD)" },
  { value: "OMR", label: "🇴🇲 Omani Rial (OMR)" },
  { value: "JOD", label: "🇯🇴 Jordanian Dinar (JOD)" },
  { value: "LBP", label: "🇱🇧 Lebanese Pound (LBP)" },
  { value: "EGP", label: "🇪🇬 Egyptian Pound (EGP)" },
  { value: "MAD", label: "🇲🇦 Moroccan Dirham (MAD)" },
  { value: "TND", label: "🇹🇳 Tunisian Dinar (TND)" },
  { value: "DZD", label: "🇩🇿 Algerian Dinar (DZD)" },
  { value: "NGN", label: "🇳🇬 Nigerian Naira (NGN)" },
  { value: "KES", label: "🇰🇪 Kenyan Shilling (KES)" },
  { value: "UGX", label: "🇺🇬 Ugandan Shilling (UGX)" },
  { value: "TZS", label: "🇹🇿 Tanzanian Shilling (TZS)" },
  { value: "ETB", label: "🇪🇹 Ethiopian Birr (ETB)" },
  { value: "GHS", label: "🇬🇭 Ghanaian Cedi (GHS)" },
  { value: "XOF", label: "🇸🇳 West African CFA Franc (XOF)" },
  { value: "XAF", label: "🇨🇲 Central African CFA Franc (XAF)" },
  { value: "MUR", label: "🇲🇺 Mauritian Rupee (MUR)" },
  { value: "BWP", label: "🇧🇼 Botswanan Pula (BWP)" },
  { value: "ZMW", label: "🇿🇲 Zambian Kwacha (ZMW)" },
  { value: "MWK", label: "🇲🇼 Malawian Kwacha (MWK)" },
  { value: "SZL", label: "🇸🇿 Swazi Lilangeni (SZL)" },
  { value: "LSL", label: "🇱🇸 Lesotho Loti (LSL)" },
  { value: "NAD", label: "🇳🇦 Namibian Dollar (NAD)" },
  { value: "BND", label: "🇧🇳 Brunei Dollar (BND)" },
  { value: "FJD", label: "🇫🇯 Fijian Dollar (FJD)" },
  { value: "PGK", label: "🇵🇬 Papua New Guinea Kina (PGK)" },
  { value: "WST", label: "🇼🇸 Samoan Tala (WST)" },
  { value: "TOP", label: "🇹🇴 Tongan Pa'anga (TOP)" },
  { value: "VUV", label: "🇻🇺 Vanuatu Vatu (VUV)" },
  { value: "SBD", label: "🇸🇧 Solomon Islands Dollar (SBD)" },
  { value: "KID", label: "🇰🇮 Kiribati Dollar (KID)" },
  { value: "LYD", label: "🇱🇾 Libyan Dinar (LYD)" },
  { value: "SDG", label: "🇸🇩 Sudanese Pound (SDG)" },
  { value: "SSP", label: "🇸🇸 South Sudanese Pound (SSP)" },
  { value: "SOS", label: "🇸🇴 Somali Shilling (SOS)" },
  { value: "DJF", label: "🇩🇯 Djiboutian Franc (DJF)" },
  { value: "ERN", label: "🇪🇷 Eritrean Nakfa (ERN)" },
  { value: "CDF", label: "🇨🇩 Congolese Franc (CDF)" },
  { value: "RWF", label: "🇷🇼 Rwandan Franc (RWF)" },
  { value: "BIF", label: "🇧🇮 Burundian Franc (BIF)" },
  { value: "SCR", label: "🇸🇨 Seychellois Rupee (SCR)" },
  { value: "KMF", label: "🇰🇲 Comorian Franc (KMF)" },
  { value: "AOA", label: "🇦🇴 Angolan Kwanza (AOA)" },
  { value: "MZN", label: "🇲🇿 Mozambican Metical (MZN)" },
  { value: "MGA", label: "🇲🇬 Malagasy Ariary (MGA)" },
  { value: "LRD", label: "🇱🇷 Liberian Dollar (LRD)" },
  { value: "SLL", label: "🇸🇱 Sierra Leonean Leone (SLL)" },
  { value: "GMD", label: "🇬🇲 Gambian Dalasi (GMD)" },
  { value: "GNF", label: "🇬🇳 Guinean Franc (GNF)" },
  { value: "CVE", label: "🇨🇻 Cape Verdean Escudo (CVE)" },
  { value: "STN", label: "🇸🇹 São Tomé and Príncipe Dobra (STN)" },
  { value: "XPF", label: "🇵🇫 CFP Franc (XPF)" },
  { value: "AMD", label: "🇦🇲 Armenian Dram (AMD)" },
  { value: "AZN", label: "🇦🇿 Azerbaijani Manat (AZN)" },
  { value: "GEL", label: "🇬🇪 Georgian Lari (GEL)" },
  { value: "KZT", label: "🇰🇿 Kazakhstani Tenge (KZT)" },
  { value: "KGS", label: "🇰🇬 Kyrgyzstani Som (KGS)" },
  { value: "TJS", label: "🇹🇯 Tajikistani Somoni (TJS)" },
  { value: "TMT", label: "🇹🇲 Turkmenistani Manat (TMT)" },
  { value: "UZS", label: "🇺🇿 Uzbekistani Som (UZS)" },
  { value: "MNT", label: "🇲🇳 Mongolian Tugrik (MNT)" },
  { value: "AFN", label: "🇦🇫 Afghan Afghani (AFN)" },
  { value: "PKR", label: "🇵🇰 Pakistani Rupee (PKR)" },
  { value: "LKR", label: "🇱🇰 Sri Lankan Rupee (LKR)" },
  { value: "NPR", label: "🇳🇵 Nepalese Rupee (NPR)" },
  { value: "BTN", label: "🇧🇹 Bhutanese Ngultrum (BTN)" },
  { value: "BDT", label: "🇧🇩 Bangladeshi Taka (BDT)" },
  { value: "MMK", label: "🇲🇲 Myanmar Kyat (MMK)" },
  { value: "LAK", label: "🇱🇦 Lao Kip (LAK)" },
  { value: "KHR", label: "🇰🇭 Cambodian Riel (KHR)" },
  { value: "MOP", label: "🇲🇴 Macanese Pataca (MOP)" },
  { value: "BMD", label: "🇧🇲 Bermudian Dollar (BMD)" },
  { value: "BBD", label: "🇧🇧 Barbadian Dollar (BBD)" },
  { value: "BZD", label: "🇧🇿 Belize Dollar (BZD)" },
  { value: "GTQ", label: "🇬🇹 Guatemalan Quetzal (GTQ)" },
  { value: "HNL", label: "🇭🇳 Honduran Lempira (HNL)" },
  { value: "NIO", label: "🇳🇮 Nicaraguan Córdoba (NIO)" },
  { value: "CRC", label: "🇨🇷 Costa Rican Colón (CRC)" },
  { value: "PAB", label: "🇵🇦 Panamanian Balboa (PAB)" },
  { value: "DOP", label: "🇩🇴 Dominican Peso (DOP)" },
  { value: "HTG", label: "🇭🇹 Haitian Gourde (HTG)" },
  { value: "JMD", label: "🇯🇲 Jamaican Dollar (JMD)" },
  { value: "TTD", label: "🇹🇹 Trinidad and Tobago Dollar (TTD)" },
  { value: "XCD", label: "🇦🇬 East Caribbean Dollar (XCD)" },
  { value: "AWG", label: "🇦🇼 Aruban Florin (AWG)" },
  { value: "ANG", label: "🇦🇳 Netherlands Antillean Guilder (ANG)" },
  { value: "SRD", label: "🇸🇷 Surinamese Dollar (SRD)" },
  { value: "GYD", label: "🇬🇾 Guyanese Dollar (GYD)" },
  { value: "UYU", label: "🇺🇾 Uruguayan Peso (UYU)" },
  { value: "PYG", label: "🇵🇾 Paraguayan Guarani (PYG)" },
  { value: "BOB", label: "🇧🇴 Bolivian Boliviano (BOB)" },
  { value: "PEN", label: "🇵🇪 Peruvian Sol (PEN)" },
  { value: "CLP", label: "🇨🇱 Chilean Peso (CLP)" },
  { value: "COP", label: "🇨🇴 Colombian Peso (COP)" },
  { value: "VES", label: "🇻🇪 Venezuelan Bolívar (VES)" },
  { value: "FKP", label: "🇫🇰 Falkland Islands Pound (FKP)" },
  { value: "PST", label: "🇵🇸 Palestinian Shekel (PST)" },
];
